# -*- coding: utf-8 -*-
"""중복제거전처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-nPhimyGWrY7h8Vtcx28F48tajmKgY5k
"""

import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

import numpy as np
from tqdm import tqdm, tqdm_notebook
import pandas as pd

df = pd.read_csv('통문서서서서.csv', encoding='euc-kr')
title=df.drop_duplicates(['키워드'])
title

fc_name = '키키최종.csv'
df.to_csv(fc_name,index=False, encoding="utf-8-sig")

